In [3]:
import numpy as np

# generater numpy array
arr = [[1, 2, 3], [4, 5, 6]]
nparr = np.array(arr, dtype=np.float32)

print(repr(nparr))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)


In [4]:
# call by reference
nparr1 = nparr
print(nparr1)

nparr[0][0] = 100
print(nparr1)

# call by value - by copy()
nparr2 = nparr.copy()
print(nparr2)

nparr[0][0] = 1
print(nparr2)

[[1. 2. 3.]
 [4. 5. 6.]]
[[100.   2.   3.]
 [  4.   5.   6.]]
[[100.   2.   3.]
 [  4.   5.   6.]]
[[100.   2.   3.]
 [  4.   5.   6.]]


In [5]:
arr = np.arange(-1, 5.5)
print(repr(arr))

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])


In [6]:
# reshaping arr
arr = np.arange(8)
print(repr(arr))

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))

array([0, 1, 2, 3, 4, 5, 6, 7])
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])


In [7]:
# reshaping arr
arr = np.arange(8)
print(repr(arr))

reshaped_arr = np.reshape(arr, (2, 2, 2))
print(repr(reshaped_arr))

array([0, 1, 2, 3, 4, 5, 6, 7])
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])


In [8]:
# reshaping arr
arr = np.arange(16)
print(repr(arr))

# -1 : 16/(2*2)
reshaped_arr = np.reshape(arr, (2, 2, -1))
print(repr(reshaped_arr))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])


In [9]:
# matrix transpose
arr = np.arange(4)
arr = np.reshape(arr, (2, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3]])
arr shape: (2, 2)
array([[0, 2],
       [1, 3]])
transposed shape: (2, 2)


In [10]:
# axes
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
transposed = np.transpose(arr, axes=(1, 2, 0))
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print('')
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))



array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])
arr shape: (3, 4, 2)

array([[[ 0,  8, 16],
        [ 1,  9, 17]],

       [[ 2, 10, 18],
        [ 3, 11, 19]],

       [[ 4, 12, 20],
        [ 5, 13, 21]],

       [[ 6, 14, 22],
        [ 7, 15, 23]]])
transposed shape: (4, 2, 3)


In [11]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [12]:
arr = np.array([[1, 2], [3, 4]])
arr = np.zeros_like(arr)
print(repr(arr))

array([[0, 0],
       [0, 0]])
